using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure
{
    public enum AcoesEnum
    {
        MGLU3,
        HAPV3,
        ITUB4,
        BBDC4,
        CIEL3,
        LREN3,
        FNAM11,
        VALE3,
        PETR4,
        B3SA3,
        COGN3,
        MRVE3,
        BRFS3,
        CVCB3,
        AZUL4,
        ABEV3,
        SUZB3,
        GNDI3,
        VVAR3,
        JBSS3,
        RADL3,
        EMBR3,
        CSNA3,
        USIM5,
        GGBR4,
        GOAU4,
        CMIG4,
        OIBR4,
        CYRE3,
        EQTL3,
        WEGE3,
        MULT3,
        UGPA3,
        CCRO3,
        YDUQ3,
        ENBR3,
        RAIL3,
        SBSP3,
        CPFE3,
        SBFG3,
        HYPE3,
        PCAR3,
        IGTA3,
        LAME4,
        CPLE6,
        QUAL3,
        LWSA3,
        SOMA3,
        RAIZ4,
        GOLL4,
        MRFG3,
        ITSA4,
        NTCO3,
        SEQL3,
        BEEF3,
        RENT3,
        CESP6,
        CPLE3,
        BRKM5,
        BRAP4,
        BRDT3
    }
}
